version: "3.8"
name: meeting-app-next-nest
services:
  server:
    container_name: meeting-app-next-nest-server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/server-nest/dockerfile.dev
    ports:
      - ${SERVER_PORT}:3131
    volumes:
      - .:/main
      - /main/node_modules/
    env_file:
      - ./.env.dev
    depends_on:
      - postgres
    command: >
      sh -c "
        yarn workspace server-nest migrate:develop
        yarn workspace server-nest generate:develop
        yarn workspace server-nest start:dev
      "
    networks:
      - nginx.docker
      - meeting-app-next-nest-server-dev-network
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: meeting-app-next-nest-postgres
    env_file:
      - ./.env.dev
    volumes:
      - db:/var/lib/postgresql/data
      - ./apps/server/init-db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - meeting-app-next-nest-server-dev-network

  client:
    container_name: meeting-app-next-nest-client
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./apps/client/dockerfile.dev
    ports:
      - ${CLIENT_PORT}:3000
    volumes:
      - .:/main
      - /main/node_modules/
    command: yarn workspace client dev

volumes:
  db:
    driver: local

networks:
  nginx.docker:
    name: nginx.docker
    external: true
  meeting-app-next-nest-server-dev-network:

